version: '3.4'

services:
  main:
    container_name: autobookmark
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/home/user/project:delegated
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
        read_only: true
    cap_add: 
      - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/user/project
    # ports:
      # - "8080:80"
      # - 5173:5173
    # extra_hosts:
    #   - host.docker.internal:host-gateway 
